version: "3.8"
services:
  mongodb:
    image: mongo:5
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - 80:3000
    environment:
      - CONNECT_STRING=$CONNECT_STRING
volumes:
  db: