version: "3.8"
services:
  mongodb:
    image: mongo:5
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=bunkermgr
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - bunker-net
  app:
    build: .
    depends_on:
      - mongodb
    restart: always
    ports:
      - "3000:3000"
    env_file: 
      - .env
    networks:
      - bunker-net
networks:
  bunker-net:
