version: "3.8"
services:
  mongodb:
    image: mongo:5
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - bunker-net
  app:
    build: .
    command: npm run start:prod
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bunker-net
networks:
  bunker-net:
