version: "3.8"
services:
  mongodb:
    image: mongo:5
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:27017
    volumes:
      - db:/data/db
  app:
    build: .
    command: npm run start:prod
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:3000
volumes:
  db:
