version: '3'

services:
  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    env_file: 
      - .env
