version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    env_file: 
      - .env
    working_dir: /app
