name: Test all

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.4'

      - name: Upgrade NPM
        run: npm install -g npm
      
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Budapest"

      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run test
